CompileFlags:
  Remove: 
  [-fmodule-mapper=CMakeFiles\MyExecutable.dir\src\main.cpp.obj.modmap,
  -fdeps-target=CMakeFiles\MyExecutable.dir\src\main.cpp.obj,
  -fdeps-file=CMakeFiles\MyExecutable.dir\src\main.cpp.obj.ddi,
  -fdeps-format=p1689r5,-fmodules-ts,-mno-direct-extern-access, 
  -fconserve-stack, -fno-allow-store-data-races, -mfunction-return=thunk-extern,
  -mindirect-branch-cs-prefix, -mindirect-branch-register, -mindirect-branch=thunk-extern, 
  -mskip-rax-setup, -mpreferred-stack-boundary=3, -mno-fp-ret-in-387 
  ]
  Add: [-IC:/msys64/mingw64/include/,-isystem,-std=c++23]

InlayHints:
  BlockEnd: No
  Designators: Yes
  Enabled: Yes
  ParameterNames: Yes
  DeducedTypes: Yes
  TypeNameLimit: 24